### ISSUE TITLE
数据量大时，SortableTree非常的卡顿

### ISSUE THREAD

**Issue by johnnychengchj123** [ant-design/pro-editor#111]
node16
react18 
代码如下
[index.md](https://github.com/ant-design/pro-editor/files/13496940/index.md)
展开和收起时，要卡几秒.....

**Comment by arvinxx** [comment]
能否给出一个可复现 demo？我们做下测试

**Comment by ONLY-yours** [comment]
来个 CodeSandBox 看看呢

**Comment by johnnychengchj123** [comment]
> 能否给出一个可复现 demo？我们做下测试

这个链接哈，我这里电脑巨卡无比.....我真实情况下，treeData真需要这么大的.....
https://codesandbox.io/p/sandbox/long-water-d8hlst?file=%2Fsrc%2FApp.js%3A3934%2C23

**Comment by arvinxx** [comment]
> > 能否给出一个可复现 demo？我们做下测试
> 
> 这个链接哈，我这里电脑巨卡无比.....我真实情况下，treeData真需要这么大的..... https://codesandbox.io/p/sandbox/long-water-d8hlst?file=%2Fsrc%2FApp.js%3A3934%2C23

了解了，可能得研究下做虚拟化

**Comment by johnnychengchj123** [comment]
> > > 能否给出一个可复现 demo？我们做下测试
> > 
> > 
> > 这个链接哈，我这里电脑巨卡无比.....我真实情况下，treeData真需要这么大的..... https://codesandbox.io/p/sandbox/long-water-d8hlst?file=%2Fsrc%2FApp.js%3A3934%2C23
> 
> 了解了，可能得研究下做虚拟化

请问这块的优化, 有什么后续排期计划嘛..........😄

**Comment by ONLY-yours** [comment]
> > > > 能否给出一个可复现 demo？我们做下测试
> > > 
> > > 
> > > 这个链接哈，我这里电脑巨卡无比.....我真实情况下，treeData真需要这么大的..... https://codesandbox.io/p/sandbox/long-water-d8hlst?file=%2Fsrc%2FApp.js%3A3934%2C23
> > 
> > 
> > 了解了，可能得研究下做虚拟化
> 
> 请问这块的优化, 有什么后续排期计划嘛..........😄

有的，我们在考虑是在组件里面加，还是提供一个 demo， 整一整这个，提供一个方案 @rdmclin2

**Comment by johnnychengchj123** [comment]
> > > > > 能否给出一个可复现 demo？我们做下测试
> > > > 
> > > > 
> > > > 这个链接哈，我这里电脑巨卡无比.....我真实情况下，treeData真需要这么大的..... https://codesandbox.io/p/sandbox/long-water-d8hlst?file=%2Fsrc%2FApp.js%3A3934%2C23
> > > 
> > > 
> > > 了解了，可能得研究下做虚拟化
> > 
> > 
> > 请问这块的优化, 有什么后续排期计划嘛..........😄
> 
> 有的，我们在考虑是在组件里面加，还是提供一个 demo， 整一整这个，提供一个方案 @rdmclin2

👏🏻👏感谢.....不知道2024.1.1可以优化好嘛....

**Comment by rdmclin2** [comment]
@johnnychengchj123 已支持虚拟滚动
