### ISSUE TITLE
DraggablePanel 不支持 maxWidth，拖拽面板能超出容器范围

### ISSUE THREAD

**Issue by zhengshuai1001** [ant-design/pro-editor#114]
![Kapture 2023-12-05 at 19 24 16](https://github.com/ant-design/pro-editor/assets/9513530/2709942b-3d4a-4828-8597-1866e29db808)

**Comment by ONLY-yours** [comment]
thanks 
https://github.com/ant-design/pro-editor/pull/115

**Comment by ONLY-yours** [comment]
released by 0.30.0
