### ISSUE TITLE
getPrefix 需要改造

### ISSUE THREAD

**Issue by ONLY-yours** [ant-design/pro-editor#118]
目前 getPrefix 取的方法有好几个，一个是 theme 下面，一个是 utils 下面，而且都是写死的 studio 前缀

需要改造统一为 继承 antd 的 prefix ，然后在后面加 -studio，即getPrefix-studio

现在写死后用户无法通过任何方法去改动并且覆盖样式（less这种特别hack的除外），最好在 Editor Provider 上提供一个能力支持，类似 ProComponents

**Comment by arvinxx** [comment]
getPrefix 应该拿到的是 editor吧，不是 studio ？

**Comment by ONLY-yours** [comment]
> getPrefix 应该拿到的是 editor吧，不是 studio ？

现在代码里面看到是 studio
后面确定下要改成 editor 么？还是 studio？
![image](https://github.com/ant-design/pro-editor/assets/52664827/121fc4a0-e229-4233-b54b-ada2dae2f37e)

**Comment by arvinxx** [comment]
全改成 editor 吧。TechUI Studio 里的prefix 是 studio。可以用这个方式确认 prefix 链路的有效性

**Comment by rdmclin2** [comment]
https://github.com/ant-design/pro-editor/pull/152

fixed
