### ISSUE TITLE
Markdown代码块没有跟随antd暗黑主题切换暗黑主题

### ISSUE THREAD

**Issue by jiabochao** [ant-design/pro-editor#132]
### 实际效果

![image](https://github.com/ant-design/pro-editor/assets/16523012/aac81674-11a7-4c1a-a071-5038edadbd6b)

### 预期效果

代码块建议加一个暗黑主题

**Comment by ONLY-yours** [comment]
好建议，当初在设计 Highlight 代码块渲染的时候，是直接指定 theme light 和 dark 来进行渲染的，没有用 token 所以导致主题在这个组件下挂了。

**Comment by ONLY-yours** [comment]
fixed
