### ISSUE TITLE
[Bug] DataPreviewer 显示为表格没有效果

### ISSUE THREAD

**Issue by rdmclin2** [ant-design/pro-editor#156]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

<img width="1066" alt="截屏2024-01-25 11 29 01" src="https://github.com/ant-design/pro-editor/assets/4705237/03721963-12fb-4eba-a46d-9aeef4e86e42">

**Comment by arvinxx** [comment]
这个在组件部分给去掉吧，把槽留出来，在 TableEditor 里再放进去？
