### ISSUE TITLE
[Question] 按教程配置后依旧出现Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by johnwick115020115** [ant-design/pro-editor#165]
### 🧐 问题描述 | Proposed Solution

React18+nextjs12，按官方文档配置transpilePackages后，只要一使用Prochat组件就会报错
![image](https://github.com/ant-design/pro-editor/assets/137584635/806e9482-3ec4-46f0-97a1-02211c88b1f9)

### 📝 补充信息 | Additional Information

![image](https://github.com/ant-design/pro-editor/assets/137584635/9cffbeab-b85b-49c1-aab1-6aff5507d5d8)
![image](https://github.com/ant-design/pro-editor/assets/137584635/ef3065f5-3b80-4654-bce8-4e22ef3e8536)

**Comment by ONLY-yours** [comment]
@johnwick115020115 ProEditor 可能文档还没更新上来，最新版本的 Nextjs 似乎不需要配置 transpilePackages 也可以运行了，可以试试看，老版本好像还需要
