### ISSUE TITLE
[Bug] DOMPurify.sanitize在运行时报错(void 0) is not a function

### ISSUE THREAD

**Issue by misakayao** [ant-design/pro-editor#177]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

1.1.1版本在使用vite打包时会有如下异常:

```
node_modules/@ant-design/pro-chat/node_modules/@ant-design/pro-editor/es/Highlight/hooks/useShiki.js (52:23): "sanitize" is not exported by "node_modules/dompurify/dist/purify.es.mjs", imported by "node_modules/@ant-design/pro-chat/node_modules/@ant-design/pro-editor/es/Highlight/hooks/useShiki.js".
```

代码运行时执行到 `return DOMPurify.sanitize("<pre><code>".concat(content, "</code></pre>"));`会直接抛异常

![image](https://github.com/ant-design/pro-editor/assets/10098771/9ab4ac4e-e032-4fd5-bfdc-995faa3e1181)

**Comment by life88** [comment]
也遇到同样的问题，网上看了一圈大概意思是 `DOMPurify` 需要使用`import DOMPurify from 'dompurify'`
的方式导入，使用 `import * as DOMPurify from 'dompurify'`的导入方式会出现这个问题。

目前我的解决方式是暂时先自定义了一个 `chatItemRenderConfig.contentRender`。我用的 `pro-chat@1.12.2` 的版本

**Comment by ONLY-yours** [comment]
sloved in 1.2.0

**Comment by misakayao** [comment]
您的邮件我已收到，感谢您的来信！
