### ISSUE TITLE
[Question] Can't install pro-editor with dependency issue

### ISSUE THREAD

**Issue by chenyuf2** [ant-design/pro-editor#184]
### 🧐 问题描述 | Proposed Solution

I can't install pro-editor. 

<img width="713" alt="Screen Shot 2024-05-15 at 3 10 22 PM" src="https://github.com/ant-design/pro-editor/assets/42945468/768d59d0-4c04-45cd-9a58-a44af30a7992">

**Comment by ONLY-yours** [comment]
looks like network problem？ cant find new version of layout-kit ？
