### ISSUE TITLE
[Bug] Markdown 组件在ProChat里，如果消息太频繁，会丢失图片

### ISSUE THREAD

**Issue by qindj** [ant-design/pro-editor#190]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

在ProChat里使用，受控方式传递messages <-一个存放消息的state，给ProChat的chats，如果对面同时(几ms的差)发送了两张图片，大概率90%以上，只会显示第一张。

图片消息格式：
`
![image](F8DBC9EB-3F6D-C0C8-2DD4-0190825816D5)
`
UUID是服务器端的图片id

ProChat用了markdownProps，将img类型转换为ant design的image组件
![image](https://github.com/ant-design/pro-editor/assets/1707762/c5f298d8-7570-45da-9292-347728a7822e)

如果不用markdownProps渲染，会出现两个裂开的图（看了下文件id是对的）

不知道是哪里出的问题，先问问这边，谢谢

### 🚦 期望结果 | Expected Behavior

同时发送的图片可以正常显示

**Comment by ONLY-yours** [comment]
感觉有可能是渲染机制的问题？

**Comment by ONLY-yours** [comment]
受控方式会导致全渲染的，疯狂触发可能会导致类似的？不确定，尝试使用 pushChats 或者 updateContent 这一类的 api 试试

**Comment by qindj** [comment]
谢谢，貌似解决了，错误的用了new Date作为消息id，消息id重复了，先关了，观察几天，有问题再开
