### ISSUE TITLE
[Bug] 官网又双叒叕 打不开了

### ISSUE THREAD

**Issue by xu756** [ant-design/pro-editor#198]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

<img width="2233" alt="image" src="https://github.com/user-attachments/assets/d2a3a2ae-b962-4714-a500-64008913145a">
官网打不开
官网打不开
官网打不开

**Comment by littlepoolshark** [comment]
![image](https://github.com/user-attachments/assets/9e07229f-7668-4849-9585-c5ab746d2763)

**Comment by ONLY-yours** [comment]
srysry

**Comment by littlepoolshark** [comment]
@ONLY-yours 还是不行啊
