### ISSUE TITLE
ProEditor 关联的leva模块，webpack5运行会报错

### ISSUE THREAD

**Issue by johnnychengchj123** [ant-design/pro-editor#87]
直接安装后，运行会报错，webpack5报如下错误
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import type { UseBoundStore } from 'zustand'
| import { StoreApiWithSubscribeWithSelector } from 'zustand/middleware'
| import type { SpecialInput, RenderFn, FolderSettings, Plugin, OnChangeHandler } from './public'
ERROR in ./node_modules/leva/src/types/internal.ts 1:12
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import type { UseBoundStore } from 'zustand'
| import { StoreApiWithSubscribeWithSelector } from 'zustand/middleware'
| import type { SpecialInput, RenderFn, FolderSettings, Plugin, OnChangeHandler } from './public'

**Comment by ONLY-yours** [comment]
能提供一些更多的信息么？我这边没有遇到你这个问题。

**Comment by johnnychengchj123** [comment]
额，我的问题，webpack后面配了一下，好了

**Comment by CNFeffery** [comment]
@johnnychengchj123 请问你后面webpack怎么配置的呢

**Comment by johnnychengchj123** [comment]
> @johnnychengchj123 请问你后面webpack怎么配置的呢

` 
{
    test: /\.(js|mjs|jsx|ts|tsx)$/,
    include: [paths.appSrc, paths.leva],
}
`
